// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ed8a629d-5a59-4011-bc69-5cd90f75714e"; //b015d86f-63b1-4dba-844d-de670d0fdad0

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAlert1Change();

float pressure1;
float temperature1;
int gas1;
int humidity1;
bool alert1;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pressure1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gas1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alert1, READWRITE, ON_CHANGE, onAlert1Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
